name: Compile and Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  TORCH_VERSION: 1.10.2

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - name: Install Python dependencies
      run: pip install -r requirements-dev.txt
    - name: Dowload libtorch
      run: |
        set -e
        curl https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-${TORCH_VERSION}%2Bcpu.zip -o libtorch.zip
        unzip libtorch.zip
        rm libtorch.zip
    - name: Generate Declarations.yaml
      run: cd pytorch && python -m tools.codegen.gen -s aten/src/ATen -d torch/share/ATen
    - name: Run tests
      run: LD_LIBRARY_PATH=$PWD/libtorch/lib:$LD_LIBRARY_PATH sbt test

